name: Telegram bot
on:
  pull_request:
    types: [opened, synchronize, closed]
  issue_comment:
    types: [created]
  workflow_run:
    workflows: [CI-main]
    types: [completed]

jobs:
  make-comment:
    name: Send comment to TG
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      PR_NAME: ${{ github.event.pull_request.title }}
      PR_BASE: ${{ github.event.pull_request.base.ref }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_MERGED: ${{ github.event.pull_request.merged_by.login }}
      REVIEW_STATE: ${{ github.event.review.state }}
      REVIEW_AUTHOR: ${{ github.event.review.user.login }}
      REVIEW_COMMENT: ${{ github.event.review.body }}
      COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
      COMMENT_URL: ${{ github.event.comment.html_url }}
      COMMENT_FILE: ${{ github.event.comment.path }}
      COMMENT_BODY: ${{ github.event.comment.body }}
      COMMENT_NUMBER: ${{ github.event.issue.number }}
      UNIVERUM_COMMIT: ${{ github.event.workflow_run.head_sha }}
      UNIVERSUM_BRANCH: ${{ github.event.workflow_run.head_branch }}
      UNIVERSUM_LOG: ${{ github.event.workflow_run.html_url }}

    steps:
    - name: Send message to TG
      run: |        
        echo TEXT: $TEXT
        echo GITHUB_ENV: $GITHUB_ENV
        echo GITHUB_CONTEXT: $GITHUB_CONTEXT
        echo GITHUB_TOKEN: $GITHUB_TOKEN

        $PR_NAME
      env:
        URL: https://api.telegram.org/bot${{ secrets.TEST }}/sendMessage
